### ISSUE TITLE
Score is not matching the one returned by GPSI web UI

### ISSUE THREAD

**Issue by shiftie** [sitespeedio/plugin-gpsi#8]
When I use this plugin to retrieve ratings, it's not matching the ones I see at https://developers.google.com/speed/pagespeed/insights/

**Comment by soulgalore** [comment]
Hi @shiftie I wonder if they are running against different versions of the API? We are using gpagespeed 5.0.3 but there's a 6.0.6 version available, but that project doesn't use a CHANGELOG so it's hard to say if they changed endpoint etc.

Here's a handy link on how to create a reproducible issue: https://www.sitespeed.io/documentation/sitespeed.io/bug-report/#explain-how-to-reproduce-your-issue so that if we update we can check if it changed or not.

Best
Peter

**Comment by shiftie** [comment]
Hi @soulgalore,

thx for answering. should I include details about my Sitespeed config or are you saying that you don't know if https://developers.google.com/speed/pagespeed/insights/ are using same version of the API as Sitespeedio GPSI plugin?

**Comment by soulgalore** [comment]
They have been using different versions, and its been hard to see what, but now when they use Lighthouse in the backend you can at least see Lighthouse version.
